#!/usr/bin/env python3

# Standard lib imports
import argparse
import json
import logging
import os
import sys

# Local project imports
import src.blockparse as blockparse
import src.exporter as exporter
from src.common import MAIN_DECOMPILER_MAX_CONTEXT_DEPTH, MAX_CONTEXT_DEPTH_INPUT_FILE


def main(args):
    # Parse bytecode
    logging.info("Reading from '%s'.", args.infile.name)
    if args.generate_interface:
        logging.info("Generating decompiler input interface")
        exporter.generate_interface()
        return
    if args.disassembly:
        blocks = blockparse.EVMDasmParser(args.infile).parse()
        metadata = {}
        # The decompiler reads bytecode.hex, thus write it empty
        bytecode = ""
    else:
        bytecode = args.infile.read().strip()
        if os.path.exists(metad := f"{args.infile.name[:-4]}_metadata.json"):
            metadata = json.load(open(metad))
        else:
            metadata = {}
        blocks = blockparse.EVMBytecodeParser(bytecode).parse()
    logging.info("Initial parsing completed.")

    logging.info("Writing facts to disk.")
    exporter.EVMBlockExporter(
        args.outdir, blocks, bytecode_hex=bytecode, metadata=metadata
    ).export()
    with open(os.path.join(args.outdir, MAX_CONTEXT_DEPTH_INPUT_FILE), "w") as f:
        f.write(f"{MAIN_DECOMPILER_MAX_CONTEXT_DEPTH}\n")


if __name__ == "__main__":
    # Configure argparse
    parser = argparse.ArgumentParser(description="Fact generation for EVM bytecode disassembly.")

    parser.add_argument(
        "-a",
        "--disassembly",
        action="store_true",
        default=False,
        help="decompile dissassembled input.",
    )

    parser.add_argument(
        "--generate_interface",
        action="store_true",
        default=False,
        help="generate .dl decompiler input interface.",
    )

    parser.add_argument(
        "infile",
        nargs="?",
        type=argparse.FileType("r"),
        default=sys.stdin,
        help="file from which decompiler input should be read (stdin by default).",
    )

    parser.add_argument(
        "outdir",
        nargs="?",
        const="",
        metavar="DIR",
        default="",
        help="produce facts for original bytecode input.",
    )

    # Parse the arguments.
    args = parser.parse_args()
    main(args)
